apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstpod-deployment
  namespace: test-ns
spec:
 replicas: 3
 selector:
   matchLabels:
    app: web-calculator
 strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
 minReadySeconds: 30
 template:
  metadata:
   name: rc-pod
   labels:
     app: web-calculator
  spec:
     # Taints: node-role.kubernetes.io/control-plane:NoSchedule
   tolerations:
   - key: "node-role.kubernetes.io/control-plane"
     operator: "Exists"
     effect: "NoSchedule"
   containers:
   - name: webcal-container
     image: rajeswaridocker97/webcalculator:VERSION
     ports:
     - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: webcal-svc-nodeport
  namespace: test-ns
spec:
 selector:
  app: web-calculator
 type: NodePort
 ports:
 - port: 8080
   targetPort: 8080
   nodePort: 31000

